### ISSUE TITLE
RSS reader scrolling stops after comming back from standby mode

### ISSUE THREAD

**Issue by lokonli** [Dashticz/dashticz#8] opened 2019-08-01 20:43 UTC
From dashticz_v3 created by [Pandabeer40](https://github.com/Pandabeer40): dashticzv3/dashticz_v3#24  

Hi there,

I want to help to test new functionality of Dashticz V3 - first 'problem' I found

I have 2 RSS blocks (nu.nl & verkeerplaza.nl) on the main screen - after 1 minute I change to standby screen (also with these RSS blocks - want to be kept informed about the traffic and news ;)) when exiting the standby mode to normal mode by changing mouse/key - main screen is visible but all RSS items are placed under eachother and there is no scrolling animation anymore

**Comment by lokonli** [comment] 2019-08-07 19:51
@pandabeer40
I cannot reproduce.
Which exact Dashticz version are you using?
Can you post your CONFIG.js here?
If the screen enters standby, and if you then directly switch back to the normal screen by moving your mouse, do you then already have issues with the news blocks?

**Comment by Pandabeer40** [comment] 2019-08-08 15:44
Hi,

 

Here’s mine custom.js – I’m working with V3 of Dashticz 3.05 master – I’m still building, I’m very happy with Dasticz but this problem still occurs on my system (Firefox / Chromium / Chrome)

 

I have also some requests:

*	Protect a button with password – after putting in the right password able to set / turn on / turn off (some buttons should be excluded for my kids 😉)
*	Possible to add something like  basketlist / shoppinglist as block – easy to share notes etc.

 

Keep up the good work – if I can test something / help you with trying some options, please let me know.

 

Best Regards,

Peter

 

Van: Lokonli <notifications@github.com> 
Verzonden: woensdag 7 augustus 2019 21:51
Aan: Dashticz/dashticz <dashticz@noreply.github.com>
CC: Pandabeer40 <peter.boermans@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Dashticz/dashticz] RSS reader scrolling stops after comming back from standby mode (#8)

 

@Pandabeer40 <https://github.com/Pandabeer40> 
I cannot reproduce.
Which exact Dashticz version are you using?
Can you post your CONFIG.js here?
If the screen enters standby, and if you then directly switch back to the normal screen by moving your mouse, do you then already have issues with the news blocks?

**Comment by Pandabeer40** [comment] 2019-08-08 15:53
Sorry,

 

Close this case 😉 I see it’s on my system not working – erased cache and now it’s running

 

Van: Lokonli <notifications@github.com> 
Verzonden: woensdag 7 augustus 2019 21:51
Aan: Dashticz/dashticz <dashticz@noreply.github.com>
CC: Pandabeer40 <peter.boermans@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Dashticz/dashticz] RSS reader scrolling stops after comming back from standby mode (#8)

 

@Pandabeer40 <https://github.com/Pandabeer40> 
I cannot reproduce.
Which exact Dashticz version are you using?
Can you post your CONFIG.js here?
If the screen enters standby, and if you then directly switch back to the normal screen by moving your mouse, do you then already have issues with the news blocks?

**Comment by lokonli** [comment] 2019-08-08 18:29
ok, thanks for the feedback. I'll close this issue.

Password protection for a block is doable. I've opened a new issue for that one. See #15 

Do you have an example of an online basketlist/shoppinglist?

**Comment by Pandabeer40** [comment] 2019-08-08 21:27
Sorry, I still get the error back on FireFox / Chrome and Chromium - can you take a closer look to my custom.js if I do something wrong?

**Comment by lokonli** [comment] 2019-08-09 05:53
I see: It's because you have a news block on your standby screen. Apparently that doesn't work.

Temporary workaround: remove the news block from the standby screen.

I'll try to fix it.

**Comment by Pandabeer40** [comment] 2019-08-09 16:43
Thnx - should be great that this will work on both screens - other (temporary) option will be probably to have different news channels (pointing to the same RSS  so NU.nl for main screen and same NU.nl but newsx block for the standby screen?) I will try your solution as well

It's for sure nice to have the news block on the standby screen ;)

Keep up the good work!

**Comment by Pandabeer40** [comment] 2019-08-09 16:57
>  other (temporary) option will be probably to have different news channels (pointing to the same RSS so NU.nl for main screen and same NU.nl but newsx block for the standby screen?

This seems to work ! So I made 2 blocks (feed) pointing to the same 'https://www.nu.nl/rss/algemeen' - one on the mainscreen the other on the standby colum defined. 

Problem for me is solved with this solution.

**Comment by lokonli** [comment] 2019-08-09 17:06
Nice trick.

**Closed** 2019-08-12 06:59 UTC
Labels: bug
